#!/bin/bash
if [ ! "$(docker ps -q -f name=n8n)" ]; then echo "Error: n8n is not running (run scripts/setup)."; exit 1; fi
docker exec n8n sh -c "n8n export:workflow --backup --output=backups/latest/workflow"
docker exec n8n sh -c "n8n export:credentials --backup --output=backups/latest/credentials"
